### ISSUE TITLE
Can't import tensorflow or tensorflow.keras

### ISSUE THREAD

**Issue by raph-431** [deganza/Install-TensorFlow-on-Mac-M1-GPU#2]
Hi. I have done the install step by step. No errors. 
I have "Python Platform: macOS-13.0-arm64-arm-64bit"
when I try to run a simple "import tensorflow.kera" in python, I get the following output: 
Any ideas? thanks so much.

>>> import tensorflow.keras
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/raphael/miniconda3/lib/python3.10/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/Users/raphael/miniconda3/lib/python3.10/site-packages/tensorflow/python/__init__.py", line 42, in <module>
    from tensorflow.python import data
  File "/Users/raphael/miniconda3/lib/python3.10/site-packages/tensorflow/python/data/__init__.py", line 21, in <module>
    from tensorflow.python.data import experimental
  File "/Users/raphael/miniconda3/lib/python3.10/site-packages/tensorflow/python/data/experimental/__init__.py", line 96, in <module>
    from tensorflow.python.data.experimental import service
  File "/Users/raphael/miniconda3/lib/python3.10/site-packages/tensorflow/python/data/experimental/service/__init__.py", line 419, in <module>
    from tensorflow.python.data.experimental.ops.data_service_ops import distribute
  File "/Users/raphael/miniconda3/lib/python3.10/site-packages/tensorflow/python/data/experimental/ops/data_service_ops.py", line 22, in <module>
    from tensorflow.python.data.experimental.ops import compression_ops
  File "/Users/raphael/miniconda3/lib/python3.10/site-packages/tensorflow/python/data/experimental/ops/compression_ops.py", line 16, in <module>
    from tensorflow.python.data.util import structure
  File "/Users/raphael/miniconda3/lib/python3.10/site-packages/tensorflow/python/data/util/structure.py", line 22, in <module>
    from tensorflow.python.data.util import nest
  File "/Users/raphael/miniconda3/lib/python3.10/site-packages/tensorflow/python/data/util/nest.py", line 34, in <module>
    from tensorflow.python.framework import sparse_tensor as _sparse_tensor
  File "/Users/raphael/miniconda3/lib/python3.10/site-packages/tensorflow/python/framework/sparse_tensor.py", line 24, in <module>
    from tensorflow.python.framework import constant_op
  File "/Users/raphael/miniconda3/lib/python3.10/site-packages/tensorflow/python/framework/constant_op.py", line 25, in <module>
    from tensorflow.python.eager import execute
  File "/Users/raphael/miniconda3/lib/python3.10/site-packages/tensorflow/python/eager/execute.py", line 21, in <module>
    from tensorflow.python.framework import dtypes
  File "/Users/raphael/miniconda3/lib/python3.10/site-packages/tensorflow/python/framework/dtypes.py", line 34, in <module>
    _np_bfloat16 = _pywrap_bfloat16.TF_bfloat16_type()
TypeError: Unable to convert function return value to a Python type! The signature was
        () -> handle

**Comment by deganza** [comment]
It is a bit contradictory what you describe.
If you say that you didn't have any errors by checking the GPU availability than you should also have no error by typing 
import tensorflow.keras

What was the output of the following code:

import sys

import tensorflow.keras
import pandas as pd
import sklearn as sk
import scipy as sp
import tensorflow as tf
import platform

print(f"Python Platform: {platform.platform()}")
print(f"Tensor Flow Version: {tf.__version__}")
print(f"Keras Version: {tensorflow.keras.__version__}")
print()
print(f"Python {sys.version}")
print(f"Pandas {pd.__version__}")
print(f"Scikit-Learn {sk.__version__}")
print(f"SciPy {sp.__version__}")
gpu = len(tf.config.list_physical_devices('GPU'))>0
print("GPU is", "available" if gpu else "NOT AVAILABLE")

**Comment by raph-431** [comment]
Thanks so much for your reply.
I wasn’t clear. I didn’t get any error until I ran the code starting with
“import sys” and then I get the error mentioned…
I’m on a brand new MacBook M1 if that helps…
Maybe I’ll try to remove all my python versions and reinstall from scratch?…

**Comment by raph-431** [comment]
This is exactly what I get when I try to run the python code starting with
"import sys":

RuntimeError: module compiled against API version 0x10 but this version of
numpy is 0xf

RuntimeError: module compiled against API version 0x10 but this version of
numpy is 0xf

ImportError: numpy.core._multiarray_umath failed to import

ImportError: numpy.core.umath failed to import

Traceback (most recent call last):

  File "/Users/raphael/Documents/python for AI sound course/testgpu.py",
line 2, in <module>

    import tensorflow.keras

  File
"/Users/raphael/miniconda3/lib/python3.10/site-packages/tensorflow/__init__.py",
line 37, in <module>

    from tensorflow.python.tools import module_util as _module_util

  File
"/Users/raphael/miniconda3/lib/python3.10/site-packages/tensorflow/python/__init__.py",
line 42, in <module>

    from tensorflow.python import data

  File
"/Users/raphael/miniconda3/lib/python3.10/site-packages/tensorflow/python/data/__init__.py",
line 21, in <module>

    from tensorflow.python.data import experimental

  File
"/Users/raphael/miniconda3/lib/python3.10/site-packages/tensorflow/python/data/experimental/__init__.py",
line 96, in <module>

    from tensorflow.python.data.experimental import service

  File
"/Users/raphael/miniconda3/lib/python3.10/site-packages/tensorflow/python/data/experimental/service/__init__.py",
line 419, in <module>

    from tensorflow.python.data.experimental.ops.data_service_ops import
distribute

  File
"/Users/raphael/miniconda3/lib/python3.10/site-packages/tensorflow/python/data/experimental/ops/data_service_ops.py",
line 22, in <module>

    from tensorflow.python.data.experimental.ops import compression_ops

  File
"/Users/raphael/miniconda3/lib/python3.10/site-packages/tensorflow/python/data/experimental/ops/compression_ops.py",
line 16, in <module>

    from tensorflow.python.data.util import structure

  File
"/Users/raphael/miniconda3/lib/python3.10/site-packages/tensorflow/python/data/util/structure.py",
line 22, in <module>

    from tensorflow.python.data.util import nest

  File
"/Users/raphael/miniconda3/lib/python3.10/site-packages/tensorflow/python/data/util/nest.py",
line 34, in <module>

    from tensorflow.python.framework import sparse_tensor as _sparse_tensor

  File
"/Users/raphael/miniconda3/lib/python3.10/site-packages/tensorflow/python/framework/sparse_tensor.py",
line 24, in <module>

    from tensorflow.python.framework import constant_op

  File
"/Users/raphael/miniconda3/lib/python3.10/site-packages/tensorflow/python/framework/constant_op.py",
line 25, in <module>

    from tensorflow.python.eager import execute

  File
"/Users/raphael/miniconda3/lib/python3.10/site-packages/tensorflow/python/eager/execute.py",
line 21, in <module>

    from tensorflow.python.framework import dtypes

  File
"/Users/raphael/miniconda3/lib/python3.10/site-packages/tensorflow/python/framework/dtypes.py",
line 34, in <module>

    _np_bfloat16 = _pywrap_bfloat16.TF_bfloat16_type()

TypeError: Unable to convert function return value to a Python type! The
signature was

() -> handle

**Comment by deganza** [comment]
try the following code:

pip install numpy  --upgrade
pip install pandas  --upgrade
pip install matplotlib  --upgrade
pip install scikit-learn  --upgrade
pip install scipy  --upgrade
pip install plotly  --upgrade

**Comment by raph-431** [comment]
Dennis,

I removed everything, reinstalled from scratch and it WORKED!
Thanks so much for writing this medium note.

all the best,

Raphael

**Comment by deganza** [comment]
Very good Raphael.
Then I will close this Issue.
